version: "3.9"
services:
  web:
    build: .
    image: sit774-app:prod
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
